pipeline {
    agent any

    stages {
        stage('clone') {
            steps {
              #git branch: 'main', url: 'https://github.com/CloudTechDevOps/Terraform_CICD.git'
               git 'https://github.com/vermakshitij19/CICD.git'
            }
        }
        stage('init') {
            steps {
                sh 'terraform init'
            }
        }
         stage('plan') {
            steps {
                sh 'terraform plan'
            }
        }
    }
}
