pipeline {
    agent any

    stages {
        stage('clone') {
           steps {
               git 'https://github.com/vermakshitij19/CICD.git'
            }
        }

        stage('init') {
            steps {
                dir('terracicd') {
                    sh 'terraform init'
                }
            }
        }

        stage('plan') {
            steps {
                dir('terracicd') {
                    sh 'terraform plan'
                }
            }
        }

        stage('apply') {
            steps {
                dir('terracicd') {
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }
}
